title: Site

columns:
  - width: 1/2
    sections:
      albums: sections/albums
  - width: 1/2
    sections:
      pages:
        type: pages
        create: default
        template:
          - home
          - projects
          - services
          - about
          - contact
          - moodboard
          - error
          - default
