title: Site

columns:
  - width: 1/1
    sections:
      pages:
        type: pages
        create: default
        template:
          - home
          - projects
          - services
          - about
          - contact
          - moodboard
          - error
          - default
